# -*- coding: utf-8 -*-
"""Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q6Jok-o83UyxBMMjS9KOJkQ0MIMuN-IH
"""

# -*- coding: utf-8 -*-
  """Enhanced Restaurant Recommendation System with XGBoost and Ensemble Learning"""

  # Import necessary libraries
  import pandas as pd
  import numpy as np
  import matplotlib.pyplot as plt
  import seaborn as sns
  import plotly.express as px
  from sklearn.cluster import MiniBatchKMeans
  from sklearn.metrics import silhouette_score
  from sklearn.ensemble import VotingRegressor
  from sklearn.linear_model import LinearRegression
  from sklearn.tree import DecisionTreeRegressor
  from sklearn.neighbors import KNeighborsRegressor
  from sklearn.preprocessing import StandardScaler
  from sklearn.pipeline import Pipeline
  from sklearn.model_selection import train_test_split, GridSearchCV
  from sklearn.metrics import mean_squared_error, r2_score
  from sklearn.inspection import permutation_importance
  from sklearn.tree import plot_tree
  import xgboost as xgb
  import joblib
  import os

  # Configure plotting
  plt.style.use('ggplot')
  plt.rcParams['figure.figsize'] = (12, 6)
  sns.set_palette('viridis')

  class RestaurantRecommender:
      def __init__(self, data_path=None):
          """Initialize the recommender system"""
          self.df = None
          self.df_restaurants = None
          self.las_vegas = None
          self.kmeans = None
          self.ensemble_model = None
          self.xgb_model = None
          self.scaler = StandardScaler()

          if data_path:
              self.load_data(data_path)

      def load_data(self, file_path):
          """Load and preprocess the dataset"""
          print("Loading and preprocessing data...")
          try:
              # Load JSON data with error handling
              self.df = pd.read_json(file_path, lines=True)

              # Data preprocessing
              self._preprocess_data()
              print("✅ Data loaded and preprocessed successfully")
          except Exception as e:
              print(f"❌ Error loading data: {e}")
              raise

      def _preprocess_data(self):
          """Internal method for data preprocessing"""
          # Filter for restaurants
          self.df['is_restaurant'] = self.df['categories'].str.contains('Restaurant', case=False, na=False)
          self.df_restaurants = self.df[self.df['is_restaurant']].copy()

          # Clean data
          self.df_restaurants = self.df_restaurants.dropna(subset=['categories', 'latitude', 'longitude'])
          self.df_restaurants = self.df_restaurants[self.df_restaurants['is_open'] == 1]  # Only open restaurants
          self.df_restaurants['stars'] = self.df_restaurants['stars'].astype(float)

          # Focus on Las Vegas restaurants
          self.las_vegas = self.df_restaurants[self.df_restaurants['state'] == 'NV'].copy()

      def perform_eda(self):
          """Perform exploratory data analysis"""
          print("\nPerforming Exploratory Data Analysis...")

          # Review distribution
          plt.figure(figsize=(12,6))
          sns.countplot(x=self.df_restaurants['stars'].round())
          plt.title('Restaurant Star Ratings Distribution')
          plt.xlabel('Star Rating')
          plt.ylabel('Count')
          plt.show()

          # Top restaurants by review count and rating
          top_restaurants = self.df_restaurants.sort_values(
              by=['review_count', 'stars'], ascending=False
          ).head(20)

          plt.figure(figsize=(12,8))
          sns.barplot(x='stars', y='name', data=top_restaurants)
          plt.title('Top 20 Restaurants by Review Count and Rating')
          plt.xlabel('Star Rating')
          plt.ylabel('Restaurant Name')
          plt.tight_layout()
          plt.show()

          # Additional EDA for Las Vegas
          if self.las_vegas is not None:
              plt.figure(figsize=(10,6))
              self.las_vegas['city'].value_counts().head(10).plot(kind='bar')
              plt.title('Top 10 Cities in Nevada with Most Restaurants')
              plt.xlabel('City')
              plt.ylabel('Number of Restaurants')
              plt.xticks(rotation=45)
              plt.show()

      def cluster_restaurants(self, max_clusters=10):
          """Cluster restaurants by location with silhouette analysis"""
          if self.las_vegas is None:
              print("No Las Vegas data available")
              return

          print("\nClustering restaurants by location...")
          coords = self.las_vegas[['longitude', 'latitude']]

          # Silhouette Score Analysis
          sil_scores = []
          cluster_range = range(2, max_clusters+1)

          for k in cluster_range:
              kmeans = MiniBatchKMeans(n_clusters=k, batch_size=1000, random_state=42)
              labels = kmeans.fit_predict(coords)
              score = silhouette_score(coords, labels)
              sil_scores.append(score)
              print(f"k={k}: Silhouette Score = {score:.4f}")

          # Plot results
          plt.figure(figsize=(10,6))
          plt.plot(cluster_range, sil_scores, 'bo-', linewidth=2, markersize=8)
          plt.xlabel('Number of Clusters (k)')
          plt.ylabel('Silhouette Score')
          plt.title('Optimal Number of Clusters')
          plt.xticks(cluster_range)
          plt.grid(True)
          plt.show()

          optimal_clusters = np.argmax(sil_scores) + 2
          print(f"\nOptimal cluster count: k={optimal_clusters}")

          # Final clustering
          self.kmeans = MiniBatchKMeans(n_clusters=optimal_clusters, batch_size=1000, random_state=42)
          self.las_vegas['cluster'] = self.kmeans.fit_predict(coords)

          # Add cluster features
          self._add_cluster_features()

          # Visualize clusters
          self._visualize_clusters()

      def _add_cluster_features(self):
          """Add features based on cluster information"""
          self.las_vegas['cluster_mean_rating'] = self.las_vegas.groupby('cluster')['stars'].transform('mean')
          self.las_vegas['cluster_review_density'] = self.las_vegas.groupby('cluster')['review_count'].transform('sum')
          self.las_vegas['cluster_size'] = self.las_vegas.groupby('cluster')['name'].transform('count')

      def _visualize_clusters(self):
          """Visualize restaurant clusters"""
          fig = px.scatter_mapbox(
              self.las_vegas,
              lat="latitude",
              lon="longitude",
              color="cluster",
              size=np.log(self.las_vegas['review_count']+1),
              hover_name="name",
              hover_data=['stars', 'review_count', 'cluster_mean_rating'],
              zoom=10,
              width=1200,
              height=800,
              title="Restaurant Clusters in Las Vegas"
          )
          fig.update_layout(mapbox_style="open-street-map")
          fig.show()

      def train_models(self):
          """Train both ensemble and XGBoost models"""
          if self.las_vegas is None:
              print("No data available for training")
              return

          print("\nTraining machine learning models...")

          # Prepare features - ensure we're not using target in features
          features = ['review_count', 'cluster_mean_rating', 'cluster_review_density']
          target = 'stars'

          X = self.las_vegas[features]
          y = self.las_vegas[target]

          # Split data
          X_train, X_test, y_train, y_test = train_test_split(
              X, y, test_size=0.2, random_state=42
          )

          # Scale features
          X_train_scaled = self.scaler.fit_transform(X_train)
          X_test_scaled = self.scaler.transform(X_test)

          # 1. Train XGBoost model
          print("\nTraining XGBoost model...")
          self.xgb_model = xgb.XGBRegressor(
              n_estimators=150,
              learning_rate=0.1,
              max_depth=6,
              subsample=0.8,
              colsample_bytree=0.8,
              gamma=0.1,
              random_state=42
          )

          self.xgb_model.fit(X_train, y_train)

          # Evaluate XGBoost
          xgb_preds = self.xgb_model.predict(X_test)
          xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_preds))
          xgb_r2 = r2_score(y_test, xgb_preds)
          print(f"XGBoost RMSE: {xgb_rmse:.4f}, R²: {xgb_r2:.4f}")

          # 2. Train Ensemble model
          print("\nTraining Ensemble model...")

          # Define base models with improved parameters
          models = [
              ('lr', LinearRegression()),
              ('dt', DecisionTreeRegressor(max_depth=5, min_samples_split=10, random_state=42)),
              ('knn', Pipeline([
                  ('scaler', StandardScaler()),
                  ('model', KNeighborsRegressor(n_neighbors=15, weights='distance'))
              ]))
          ]

          # Grid search for optimal weights
          param_grid = {
              'weights': [
                  [0.3, 0.5, 0.2],  # More weight to decision tree
                  [0.2, 0.6, 0.2],  # Even more to decision tree
                  [0.4, 0.4, 0.2]   # Balanced between linear and tree
              ]
          }

          grid_search = GridSearchCV(
              VotingRegressor(models),
              param_grid,
              scoring='neg_root_mean_squared_error',
              cv=5,
              n_jobs=-1
          )

          grid_search.fit(X_train, y_train)
          self.ensemble_model = grid_search.best_estimator_
          print(f"Best weights: {grid_search.best_params_['weights']}")

          # Evaluate Ensemble
          ensemble_preds = self.ensemble_model.predict(X_test)
          ensemble_rmse = np.sqrt(mean_squared_error(y_test, ensemble_preds))
          ensemble_r2 = r2_score(y_test, ensemble_preds)
          print(f"Ensemble RMSE: {ensemble_rmse:.4f}, R²: {ensemble_r2:.4f}")

          # Add predictions to dataframe
          self.las_vegas['xgb_pred'] = self.xgb_model.predict(X)
          self.las_vegas['ensemble_pred'] = self.ensemble_model.predict(X)

          # Visualize model comparisons
          self._visualize_model_performance(X_test, y_test)

      def _visualize_model_performance(self, X_test, y_test):
          """Visualize model performance comparisons"""
          # Get predictions
          xgb_preds = self.xgb_model.predict(X_test)
          ensemble_preds = self.ensemble_model.predict(X_test)

          # Create comparison plot
          plt.figure(figsize=(12, 6))

          # Actual vs Predicted
          plt.subplot(1, 2, 1)
          plt.scatter(y_test, xgb_preds, alpha=0.3, label='XGBoost')
          plt.scatter(y_test, ensemble_preds, alpha=0.3, label='Ensemble')
          plt.plot([1, 5], [1, 5], 'k--', label='Perfect Prediction')
          plt.xlabel('Actual Rating')
          plt.ylabel('Predicted Rating')
          plt.title('Actual vs Predicted Ratings')
          plt.legend()

          # Error distribution
          plt.subplot(1, 2, 2)
          xgb_errors = y_test - xgb_preds
          ensemble_errors = y_test - ensemble_preds
          sns.kdeplot(xgb_errors, label='XGBoost Errors', fill=True)
          sns.kdeplot(ensemble_errors, label='Ensemble Errors', fill=True)
          plt.axvline(0, color='k', linestyle='--')
          plt.xlabel('Prediction Error')
          plt.ylabel('Density')
          plt.title('Error Distribution')
          plt.legend()

          plt.tight_layout()
          plt.show()

          # Feature importance
          self._plot_feature_importance()

      def _plot_feature_importance(self):
          """Plot feature importance for both models"""
          # XGBoost feature importance
          xgb_importance = self.xgb_model.feature_importances_
          features = ['review_count', 'cluster_mean_rating', 'cluster_review_density']

          plt.figure(figsize=(12, 5))

          plt.subplot(1, 2, 1)
          sns.barplot(x=xgb_importance, y=features)
          plt.title('XGBoost Feature Importance')
          plt.xlabel('Importance Score')

          # Ensemble feature importance (using permutation importance)
          result = permutation_importance(
              self.ensemble_model,
              self.scaler.transform(self.las_vegas[features]),
              self.las_vegas['stars'],
              n_repeats=10,
              random_state=42
          )
          ensemble_importance = result.importances_mean

          plt.subplot(1, 2, 2)
          sns.barplot(x=ensemble_importance, y=features)
          plt.title('Ensemble Permutation Importance')
          plt.xlabel('Importance Score')

          plt.tight_layout()
          plt.show()

      def visualize_decision_tree(self):
          """Visualize the decision tree from the ensemble"""
          if self.ensemble_model is None:
              print("Ensemble model not trained yet")
              return

          dt_model = self.ensemble_model.named_estimators_['dt']
          plt.figure(figsize=(20, 10))
          plot_tree(
              dt_model,
              feature_names=['review_count', 'cluster_mean_rating', 'cluster_review_density'],
              filled=True,
              rounded=True,
              fontsize=10,
              proportion=True
          )
          plt.title("Decision Tree Regressor from Ensemble Model")
          plt.show()

      def recommend_restaurants(self, longitude, latitude, model_type='xgb',
                              min_stars=3.5, min_reviews=50, top_n=5,
                              preferred_cuisine=None):
          """
          Get restaurant recommendations based on location and preferences

          Args:
              longitude (float): User's longitude
              latitude (float): User's latitude
              model_type (str): 'xgb' or 'ensemble' - which model to use
              min_stars (float): Minimum star rating threshold
              min_reviews (int): Minimum number of reviews threshold
              top_n (int): Number of recommendations to return
              preferred_cuisine (str): Optional cuisine preference filter

          Returns:
              pd.DataFrame: DataFrame of recommended restaurants
          """
          if self.las_vegas is None or self.kmeans is None:
              print("Models not trained or data not loaded")
              return pd.DataFrame()

          try:
              # Predict cluster
              cluster = self.kmeans.predict([[longitude, latitude]])[0]

              # Filter candidates
              recs = self.las_vegas[
                  (self.las_vegas['cluster'] == cluster) &
                  (self.las_vegas['stars'] >= min_stars) &
                  (self.las_vegas['review_count'] >= min_reviews)
              ].copy()

              if recs.empty:
                  print("No restaurants match your criteria. Try relaxing filters.")
                  return pd.DataFrame()

              # Filter by cuisine if specified
              if preferred_cuisine:
                  recs = recs[recs['categories'].str.contains(preferred_cuisine, case=False, na=False)]
                  if recs.empty:
                      print(f"No {preferred_cuisine} restaurants match your criteria.")
                      return pd.DataFrame()

              # Calculate distances
              recs = self._add_distance_features(recs, latitude, longitude)

              # Generate model scores
              features = ['review_count', 'cluster_mean_rating', 'cluster_review_density']

              if model_type.lower() == 'xgb':
                  recs['model_score'] = self.xgb_model.predict(recs[features])
              else:
                  recs['model_score'] = self.ensemble_model.predict(recs[features])

              # Composite score (60% model prediction, 40% proximity)
              recs['distance_score'] = np.exp(-recs['distance_miles'] / 2.5)
              recs['composite_score'] = 0.6 * recs['model_score'] + 0.4 * recs['distance_score']

              # Return top recommendations
              return recs.sort_values('composite_score', ascending=False).head(top_n)[
                  ['name', 'stars', 'model_score', 'review_count',
                  'distance_miles', 'address', 'categories', 'latitude', 'longitude']
              ]

          except Exception as e:
              print(f"Error in recommendation: {e}")
              return pd.DataFrame()

      def _add_distance_features(self, df, ref_lat, ref_lon):
          """Calculate distances from reference point for all restaurants"""
          lat_rad = np.radians(df['latitude'])
          lon_rad = np.radians(df['longitude'])
          ref_lat_rad = np.radians(ref_lat)
          ref_lon_rad = np.radians(ref_lon)

          dlon = lon_rad - ref_lon_rad
          dlat = lat_rad - ref_lat_rad

          a = np.sin(dlat/2)**2 + np.cos(ref_lat_rad) * np.cos(lat_rad) * np.sin(dlon/2)**2
          c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
          df['distance_miles'] = 3959 * c
          return df

      def visualize_recommendations(self, user_lat, user_lon, model_type='both',
                                min_stars=3.5, min_reviews=50, preferred_cuisine=None):
          """
          Visualize recommendations on a map

          Args:
              user_lat (float): User's latitude
              user_lon (float): User's longitude
              model_type (str): 'xgb', 'ensemble', or 'both'
              min_stars (float): Minimum star rating
              min_reviews (int): Minimum review count
              preferred_cuisine (str): Optional cuisine preference
          """
          if model_type.lower() not in ['xgb', 'ensemble', 'both']:
              print("Invalid model_type. Use 'xgb', 'ensemble', or 'both'")
              return

          # Get more recommendations to ensure diversity
          base_top_n = 10

          # Get recommendations based on model type
          recs = []

          if model_type.lower() in ['xgb', 'both']:
              xgb_recs = self.recommend_restaurants(
                  user_lon, user_lat, 'xgb', min_stars, min_reviews,
                  preferred_cuisine=preferred_cuisine,
                  top_n=base_top_n
              )
              if not xgb_recs.empty:
                  xgb_recs['model'] = 'XGBoost'
                  # Take top 5 or half of available, whichever is smaller
                  take_n = min(5, len(xgb_recs))
                  recs.append(xgb_recs.head(take_n))

          if model_type.lower() in ['ensemble', 'both']:
              ensemble_recs = self.recommend_restaurants(
                  user_lon, user_lat, 'ensemble', min_stars, min_reviews,
                  preferred_cuisine=preferred_cuisine,
                  top_n=base_top_n
              )
              if not ensemble_recs.empty:
                  ensemble_recs['model'] = 'Ensemble'
                  # Take top 5 or half of available, whichever is smaller
                  take_n = min(5, len(ensemble_recs))
                  recs.append(ensemble_recs.head(take_n))

          if not recs:
              print("No recommendations found. Try relaxing your criteria.")
              return

          all_recs = pd.concat(recs)

          # Print recommendations
          print(f"\nTop recommendations near ({user_lat}, {user_lon}):")
          print(all_recs[['name', 'stars', 'distance_miles', 'model']].to_string(index=False))

          # Visualize on map
          fig = px.scatter_mapbox(
              all_recs,
              lat="latitude",
              lon="longitude",
              hover_name="name",
              hover_data=['stars', 'distance_miles', 'model', 'categories'],
              color="model",
              color_discrete_map={'XGBoost': 'blue', 'Ensemble': 'green'},
              size=np.log(all_recs['review_count']+5),
              zoom=14,
              height=600
          )

          # Add user location
          fig.add_trace(px.scatter_mapbox(
              pd.DataFrame({'lat': [user_lat], 'lon': [user_lon], 'name': ['Your Location']}),
              lat="lat",
              lon="lon",
              hover_name="name",
              color_discrete_sequence=['red'],
              size=[15]
          ).data[0])

          # Configure layout
          fig.update_layout(
              mapbox_style="open-street-map",
              mapbox_center={"lat": user_lat, "lon": user_lon},
              margin={"r":0,"t":0,"l":0,"b":0},
              title=f"Restaurant Recommendations ({model_type} model)"
          )

          fig.show()

      def save_models(self, path='models'):
          """Save trained models to disk"""
          if not os.path.exists(path):
              os.makedirs(path)

          joblib.dump(self.kmeans, os.path.join(path, 'kmeans_model.pkl'))
          joblib.dump(self.ensemble_model, os.path.join(path, 'ensemble_model.pkl'))
          joblib.dump(self.xgb_model, os.path.join(path, 'xgb_model.pkl'))
          joblib.dump(self.scaler, os.path.join(path, 'scaler.pkl'))
          print(f"✅ Models saved to {path} directory")

      def load_models(self, path='models'):
          """Load trained models from disk"""
          try:
              self.kmeans = joblib.load(os.path.join(path, 'kmeans_model.pkl'))
              self.ensemble_model = joblib.load(os.path.join(path, 'ensemble_model.pkl'))
              self.xgb_model = joblib.load(os.path.join(path, 'xgb_model.pkl'))
              self.scaler = joblib.load(os.path.join(path, 'scaler.pkl'))
              print("✅ Models loaded successfully")
          except Exception as e:
              print(f"❌ Error loading models: {e}")

  # Example usage
  if __name__ == "__main__":
      # Initialize recommender
      recommender = RestaurantRecommender()

      import warnings
      warnings.filterwarnings("ignore", message="X does not have valid feature names")

      # Initialize recommender
      recommender = RestaurantRecommender()

      from google.colab import drive
      drive.mount('/content/drive')

  # Load the dataset
      file_path = "/content/drive/My Drive/yelp_academic_dataset_business.json"
      recommender.load_data(file_path)

      # Perform EDA
      recommender.perform_eda()

      # Cluster restaurants
      recommender.cluster_restaurants()

      # Train models
      recommender.train_models()

      # Visualize decision tree
      recommender.visualize_decision_tree()

      # Save models for later use
      recommender.save_models()

      # Test recommendations
      test_coordinates = [
          {'user': 'Strip Tourist', 'lat': 36.112852, 'lon': -115.172431},
          {'user': 'Downtown Local', 'lat': 36.169941, 'lon': -115.139830},
          {'user': 'Suburban Visitor', 'lat': 36.155011, 'lon': -115.082821}
      ]

      for user in test_coordinates:
          print(f"\nTesting for {user['user']} at ({user['lat']}, {user['lon']}):")
          recommender.visualize_recommendations(user['lat'], user['lon'], model_type='both')

          # Test with cuisine preference
          print("\nTesting with Italian cuisine preference:")
          recommender.visualize_recommendations(
              user['lat'], user['lon'],
              model_type='both',
              preferred_cuisine='Italian'
          )